import { mkdir, writeFile, readFile, unlink, stat } from "node:fs/promises";
import path from "node:path";
import { createHmac, timingSafeEqual } from "node:crypto";
import type { HeadObjectResult, PutObjectParams, StorageService, StorageVisibility } from "./types";
import { emitStorageEvent } from "./types";

/**
 * Local-disk storage for development only. Deliberately NOT under `public/`
 * — Next's static file serving would otherwise expose every object at a
 * predictable URL regardless of visibility, defeating the private/public
 * distinction entirely. Objects live under `.local-storage/` (gitignored)
 * and are served exclusively through `/api/storage/local/[...key]`, which
 * enforces the same visibility rule this provider's keys already encode
 * (every key starts with "public/" or "private/" — see objectKeys.ts).
 *
 * Signed URLs are genuine HMAC-signed, expiring tokens (keyed off the
 * existing AUTH_SECRET, so no new env var is needed) — not a stand-in that
 * merely serves everything unconditionally. This means local dev actually
 * exercises expiry/tamper-rejection behavior, not just a simulation of it.
 *
 * No `"server-only"` import here, matching src/lib/db.ts's existing
 * precedent: this module is imported both from Next (API routes/RSC pages)
 * and directly via tsx (the migration script in scripts/) — "server-only"
 * unconditionally throws outside a bundler that understands the
 * "react-server" export condition, which plain Node/tsx does not.
 */

const STORAGE_ROOT = path.join(process.cwd(), ".local-storage");

function pathFor(key: string): string {
  const resolved = path.resolve(STORAGE_ROOT, key);
  // Defense in depth: every key passed in is already generated by
  // objectKeys.ts (opaque ids, no user input), but this guarantees a key
  // can never resolve outside STORAGE_ROOT regardless of how it was built.
  if (!resolved.startsWith(STORAGE_ROOT + path.sep)) {
    throw new Error("Invalid object key");
  }
  return resolved;
}

function metaPathFor(key: string): string {
  return `${pathFor(key)}.meta.json`;
}

function signingSecret(): string {
  const secret = process.env.AUTH_SECRET;
  if (!secret) throw new Error("AUTH_SECRET is not set (required to sign local storage URLs)");
  return secret;
}

function sign(key: string, exp: number): string {
  return createHmac("sha256", signingSecret()).update(`${key}:${exp}`).digest("hex");
}

/** Used by the /api/storage/local route to verify a signed URL's query params. */
export function verifyLocalSignedUrl(key: string, exp: number, sig: string): boolean {
  if (Date.now() / 1000 > exp) return false;
  // Reject anything that isn't exactly a 64-char hex string up front. This
  // is deliberate, not merely defensive: Buffer.from(str, "hex") silently
  // truncates at the first non-hex character instead of throwing, so
  // without this check a malformed `sig` could parse down to a short (but
  // still equal-length-checked-later) byte sequence — length mismatches
  // still fail correctly today, but relying on that side effect for a
  // security-relevant comparison is fragile. This check removes the
  // ambiguity entirely.
  if (!/^[0-9a-f]{64}$/i.test(sig)) return false;
  const expected = sign(key, exp);
  const a = Buffer.from(sig, "hex");
  const b = Buffer.from(expected, "hex");
  return timingSafeEqual(a, b);
}

export class LocalStorageProvider implements StorageService {
  async putObject(params: PutObjectParams): Promise<{ key: string }> {
    emitStorageEvent({ name: "storage.upload.started", key: params.key, visibility: params.visibility, provider: "local" });
    try {
      const filePath = pathFor(params.key);
      await mkdir(path.dirname(filePath), { recursive: true });
      await writeFile(filePath, params.body);
      await writeFile(metaPathFor(params.key), JSON.stringify({ contentType: params.contentType }));
      emitStorageEvent({
        name: "storage.upload.completed",
        key: params.key,
        visibility: params.visibility,
        provider: "local",
        detail: { bytes: params.body.length },
      });
      return { key: params.key };
    } catch (err) {
      emitStorageEvent({ name: "storage.upload.failed", key: params.key, visibility: params.visibility, provider: "local" });
      throw err;
    }
  }

  async getSignedUrl(key: string, visibility: StorageVisibility, expiresInSeconds = 900): Promise<string> {
    if (visibility === "public") return this.getPublicUrl(key);
    const exp = Math.floor(Date.now() / 1000) + expiresInSeconds;
    const sig = sign(key, exp);
    emitStorageEvent({ name: "storage.signed_url.generated", key, visibility, provider: "local", detail: { expiresInSeconds } });
    return `/api/storage/local/${key}?exp=${exp}&sig=${sig}`;
  }

  getPublicUrl(key: string): string {
    return `/api/storage/local/${key}`;
  }

  async getObject(key: string): Promise<Buffer> {
    return readFile(pathFor(key));
  }

  async headObject(key: string): Promise<HeadObjectResult> {
    try {
      const stats = await stat(pathFor(key));
      let contentType: string | undefined;
      try {
        const meta = JSON.parse(await readFile(metaPathFor(key), "utf-8"));
        contentType = meta.contentType;
      } catch {
        contentType = undefined;
      }
      return { exists: true, size: stats.size, contentType };
    } catch {
      return { exists: false };
    }
  }

  async deleteObject(key: string, visibility: StorageVisibility): Promise<void> {
    await unlink(pathFor(key)).catch(() => {});
    await unlink(metaPathFor(key)).catch(() => {});
    emitStorageEvent({ name: "storage.delete.completed", key, visibility, provider: "local" });
  }
}
